<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menusData = [
            ['name' => 'Beef Caldereta', 'description' => 'Beef Caldereta is a main stay in any Filipino Kitchen. It is a type of beef stew cooked with tomato sauce and liver spread. Ingredients such as potato, carrots, bell peppers, and olives are also utilized when cooking this dish.', 'price' => 800, 'status' => 1, 'menu_selection_id' => 2, 'menus_image' => 'Beef Caldereta.jpg'],
            ['name' => 'Beef Lengua', 'description' => 'Beef tongue is one of the most delectable, tender cuts of beef due to its high fat to protein ratio and very flavorful due to the amount of exercise the tongue muscle gets. It can be boiled for soup, pickled, roasted, braised in sauce or seared for a crispy outer texture.', 'price' => 1200, 'status' => 1, 'menu_selection_id' => 2, 'menus_image' => 'Beef Lengua.jpg'],
            ['name' => 'Beef Broccoli', 'description' => 'Beef Broccoli is a sweet and savory dish made by cooking sliced beef pieces and broccoli in a sauce made with soy sauce, oyster sauce, sugar, ginger, garlic, sesame seeds. pepper and salt.', 'price' => 800, 'status' => 1, 'menu_selection_id' => 2, 'menus_image' => 'Beef Broccoli.jpg'],
            ['name' => 'Beef with mushroom', 'description' => "Beef and Mushrooms is easy to make and cooks in one pan. Loaded with tender beef and rich mushroom gravy, it's hearty, tasty and perfect to eat with rice.", 'price' => 800, 'status' => 1, 'menu_selection_id' => 2, 'menus_image' => 'Beef with Mushroom.jpg'],
            ['name' => 'Beef Korean BBQ', 'description' => "Beef Korean BBQ (Bulgogi) is a Korean dish of grilled marinated beef, literally means “fire meat. It is Korea’s most popular beef dishes that is made from thinly sliced sirloin or another prime cut of beef (rib eye).", 'price' => 800, 'status' => 1, 'menu_selection_id' => 2, 'menus_image' => 'Korean Style BBQ Beef.jpg'],
            ['name' => 'Roast beef with siding and gravy', 'description' => 'a beef dish cooked by roasting in an oven. The beef is simply coated with olive oil and sprinkled with salt and pepper before roasting.', 'price' => 800, 'status' => 1, 'menu_selection_id' => 2, 'menus_image' => 'Roast beef with Siding and Gravy.jpg'],

            ['name' => 'Cordon Bleu', 'description' => 'Cordon bleu is a dish that traditionally consists of meat wrapped around cheese, then breaded and pan-fried or deep-fried.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Cordon Bleu.jpg'],
            ['name' => 'Honey garlic chicken', 'description' => 'A classic combination of honey, soy sauce and garlic working together to produce a sticky, sweet sauce to coat golden tender chicken pieces.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Honey Garlic Chicken.jpg'],
            ['name' => 'Buffalo Wings', 'description' => 'Buffalo wing, also called hot wing, chicken wing, or wing, deep-fried unbreaded chicken wings or drumsticks coated with a vinegar-and-cayenne-pepper hot sauce mixed with butter.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Buffalo Chicken Wings.jpg'],
            ['name' => 'Grilled Chicken with BBQ Sauce', 'description' => 'Barbecue chicken is often seasoned or coated in a spice rub, barbecue sauce, or both. Chicken parts or entire chickens that are barbecued or grilled.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Grilled Chicken with BBQ Sauce.jpg'],
            ['name' => 'Chicken Teriyaki', 'description' => 'Chicken Teriyaki is a simple recipe for teriyaki chicken that makes use of boneless and skinless chicken breasts, a homemade teriyaki marinade, with gorgeous sesame seeds for garnish.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Chicken Teriyaki.jpg'],
            ['name' => 'Chicken Pastel', 'description' => 'Chicken Pastel is a Filipino creamy chicken stew, a hearty stew made of diced chicken meat, sausages, mushrooms, peas, and carrots in a rich, creamy sauce.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Chicken Pastel.jpg'],
            ['name' => 'Chicken Caldereta', 'description' => 'Chicken Caldereta, a Filipino chicken stew dish, is a variation of the original Spanish recipe, simmered to perfect tenderness in a spicy tomato sauce with potatoes, bell peppers, and green olives.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Chicken Caldereta.jpg'],
            ['name' => 'Chicken Fillet with Dip', 'description' => 'Fried Chicken Breast with Creamy Lemon Sauce Dip is a yummy fried chicken variation. This recipe involves skinless and boneless chicken breast and a creamy dip that you will love.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Chicken Fillet with Dip.jpg'],
            ['name' => 'Fried Chicken with Gravy', 'description' => "Filipino-style Fried Chicken marinated in citrus and spices and fried to golden perfection. Tasty and crunchy, it's sure to be a family favorite!", 'price' => 600, 'status' => 1, 'menu_selection_id' => 3, 'menus_image' => 'Fried Chicken with Gravy.jpeg'],

            ['name' => 'Buko Salad', 'description' => 'Made with shredded sweet young coconut meat, fruit cocktail, nata de coco, kaong, pineapple chunks, condensed milk, and cream.', 'price' => 500, 'status' => 1, 'menu_selection_id' => 8, 'menus_image' => 'Buko Salad.jpg'],
            ['name' => 'Fruit Salad', 'description' => 'a Filipino fruit salad needs only three ingredients that are the fruit cocktail, sweetened condensed milk, and cream', 'price' => 500, 'status' => 1, 'menu_selection_id' => 8, 'menus_image' => 'Buko Fruit Salad.jpg'],
            ['name' => 'Buko Pandan', 'description' => 'A popular Filipino Dessert made using young coconut, pandan leaves, and sago pearls.', 'price' => 500, 'status' => 1, 'menu_selection_id' => 8, 'menus_image' => 'Buko Pandan.jpg'],
            ['name' => 'Buko Lychee', 'description' => 'A delicious dessert treats rich in Vitamin C, and Vitamin B-complex made with lychee, young coconut, and cream.', 'price' => 500, 'status' => 1, 'menu_selection_id' => 8, 'menus_image' => 'Buko Lychee.jpg'],
            ['name' => 'Coffee jelly', 'description' => 'a delicious coffee-flavored cubed gelatin in a thick coffee-infused sweetened cream. A great dessert for coffee lovers', 'price' => 500, 'status' => 1, 'menu_selection_id' => 8, 'menus_image' => 'Coffee Jelly.jpg'],

           
            ['name' => 'Iced tea Lemon', 'description' => "A low-sugar, low-calorie way to add a range of vitamins and minerals to your diet. Grating lemon zest into your tea also adds the peel's limonene.", 'price' => 300, 'status' => 1, 'menu_selection_id' => 9, 'menus_image' => 'Iced Tea Lemon.jpg'],
            ['name' => 'Red Iced Tea', 'description' => 'a variation of iced tea made with pomegranate juice mixed with brewed with black tea.', 'price' => 300, 'status' => 1, 'menu_selection_id' => 9, 'menus_image' => 'Red Iced Tea.jpg'],
            ['name' => 'Blue Lemonade', 'description' => "Made with blueberries and blackberries, no artificial colors of flavors here. It's like regular lemonade that is made different refreshment.", 'price' => 300, 'status' => 1, 'menu_selection_id' => 9, 'menus_image' => 'Blue Lemonade.jpg'],
            ['name' => 'Cucumber Lemonade', 'description' => 'A naturally sweetened cucumber lemonade is made with fresh cucumber juice, honey, and lemon juice.', 'price' => 300, 'status' => 1, 'menu_selection_id' => 9, 'menus_image' => 'Cucumber Lemonade.jpg'],
            ['name' => "Sago’t Gulaman", 'description' => "Sago at Gulaman with sago pearls, grass jelly, and brown sugar syrup is a tropical cooler you'll love year-round. It's refreshing and delicious as it is fun to eat!", 'price' => 300, 'status' => 1, 'menu_selection_id' => 9, 'menus_image' => "Sago't Gulaman.jpg"],

            ['name' => 'Fish Fillet with Tartar Sauce', 'description' => "A Deboned fish coated with all-purpose flour, breadcrumbs served with Tartar sauce which is a cold dipping sauce that is usually served alongside seafood, mainly fish. It's a creamy condiment that is known for its rich and tangy flavor.", 'price' => 500, 'status' => 1, 'menu_selection_id' => 4, 'menus_image' => 'Fish Fillet with Tartar Sauce.jpg'],
            ['name' => 'Sweet and Sour Fish Fillet', 'description' => 'Sweet and sour fish is dish where fried fish is topped with stir fried veggies like carrots, and bell peppers (capsicum) and thick sweet and sour sauce.', 'price' => 500, 'status' => 1, 'menu_selection_id' => 4, 'menus_image' => 'Fish Sweet and Sour.jpg'],
            ['name' => 'Fish and Tofu in Black Bean Sauce', 'description' => 'classic Filipino fish dish made with bangus (milkfish), pan -fried, then simmered in a Tocho sauce flavored with ginger, garlic, onions, and tausi (salted black beans), Tofu cubes and tomatoes are added to complete the entree.', 'price' => 500, 'status' => 1, 'menu_selection_id' => 4, 'menus_image' => 'Fish and Tofu in Black Bean Sauce.webp'],

            ['name' => 'Baked Macaroni', 'description' => 'Baked Macaroni is a Filipino-style pasta casserole with a meaty sauce and a layer of creamy béchamel sauce topped with melted cheese.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 6, 'menus_image' => 'Baked Macaroni.jpg'],
            ['name' => 'Carbonara', 'description' => 'Filipino-style Pasta Carbonara loaded with crisp bacon, sauteed mushrooms, and flavorful cream sauce is a tasty pasta dish the whole family is sure to love.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 6, 'menus_image' => 'Carbonara.jpg'],
            ['name' => 'Charlie Chan', 'description' => 'A stir-fried spaghetti noodles in a sticky sweet, savory, and spicy oriental sauce with chicken, shiitake mushrooms, and peanuts.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 6, 'menus_image' => 'Charlie Chan Pasta.jpg'],
            ['name' => 'Spaghetti', 'description' => 'Filipino Spaghetti is the Pinoy version of Spaghetti with meat sauce. This version has a sweet tomato based sauce with lots of meat ingredients such as ground pork, luncheon meat, and hotdogs.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 6, 'menus_image' => 'Spaghetti.jpg'],
            ['name' => 'Sotanghon Canton Guisado', 'description' => 'This is an easy stir-fry recipe which starts with cooking the chicken and shrimps and later adding the vegetables and noodles. Pancit is a mainstay during birthdays, fiestas or family gatherings.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 6, 'menus_image' => 'Sotanghon Canton Guisado.jpg'],
            ['name' => 'Mixed Bihon Canton Guisado', 'description' => 'a Filipino dish of Chinese origin which combines yellow wheat noodles and a variety of meat, seafood, and vegetables, blended with a flavorful mixture of soy and oyster sauce.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 6, 'menus_image' => 'Mixed Bihon Canton Guisado.jpg'],
            ['name' => 'Pancit Canton', 'description' => 'Pancit Canton it is a type of Lo Mein or tossed noodles known as flour sticks. This dish is made with wheat noodles and assorted meat and vegetables.', 'price' => 600, 'status' => 1, 'menu_selection_id' => 6, 'menus_image' => 'Pancit Canton.jpg'],

            ['name' => 'Gravious Pork', 'description' => 'A pork with white sauce, buggy beans, corn, butter and a French fries on top.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Gravious Pork.jpeg'],
            ['name' => 'Pork Korean BBQ', 'description' => 'Korean BBQ so unique is the way the meat is prepared. High-quality beef, pork, or chicken is first cut into small, tender pieces. You can marinate the meat using a variety of sauces to give the dish a unique flavor or simply slice it into bite-sized fatty chunks', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Pork Korean BBQ.jpeg'],
            ['name' => 'Spicy Pork Ribs', 'description' => 'a cut of pork from the loin or side between the shoulder and back legs. Pork ribs come in three basic cuts – back ribs, spareribs, and country-style ribs – depending on the section of the hog where they originated.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Spicy Pork Ribs.jpg'],
            ['name' => 'Baby Back Ribs', 'description' => 'Baby back ribs come from the parts of the ribs that are connected to the backbone, beneath the loin muscle, and are curved where the meet the spine.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Baby Back Ribs.jpg'],
            ['name' => 'Pork with Mushroom', 'description' => 'Pork Chops in Creamy Mushroom Sauce is a special dish that comes occasionally on a Filipino gathering feast, prepared with pan fried pork chops served on a creamy sauce with sliced mushrooms.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Pork with Mushroom.jpg'],
            ['name' => 'Pork Lengua', 'description' => 'Tender Pork Lengua Recipe with creamy white sauce. Cooked in pressure cooker to cut the cooking time. An all-time favorite Filipino delicacy.', 'price' => 1000, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Lengua.jpg'],
            ['name' => 'Pork Broccoli', 'description' => 'Pork broccoli is together in a delicious variance of seasonings and sauces, this tasty dish is absolutely a crowd favorite! The contrast between the tenderness of the pork and the crunchiness of the veggies just makes eating this dish more enjoyable. ', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Pork Broccoli.jpg'],
            ['name' => 'Pork Mocron', 'description' => "Morcon is a Filipino meat roll stuffed with sausage or hotdogs, carrots, pickles, cheese, and egg. This is considered as a holiday dish and is usually served during Christmas (Noche Buena) and New Year’s Eve (Media Noche).", 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Pork Morcon.jpg'],
            ['name' => 'Pork Teriyaki', 'description' => 'a cooking technique in which foods are broiled or grilled with a glaze of soy sauce, mirin, and sugar. The best side dishes to serve with teriyaki pork chops are rice, noodles, steamed vegetables, and salad.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Pork Tereyaki.jpg'],
            ['name' => 'Pork Kare Kare', 'description' => 'A traditional Filipino stew complimented with a thick savory peanut sauce. The commonly used meats for this dish are ox tail, tripe, and pork leg; on some occasions goat and chicken meat are also used. Besides the peanuts, this dish depends on the shrimp paste (on the side) in order to be fully enjoyed.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Pork Kare Kare.jpg'],
            ['name' => 'Pork Menudo', 'description' => 'Pork Menudo is a Filipino pork stew dish with carrots and potato. It is stewed in a tomato-based sauce and best eaten with rice.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Porky Menudo.jpg'],
            ['name' => 'Pork Caldareta', 'description' => 'Pork Caldereta is a Filipino tomato-based stew. It is composed of cubed pork, potato, carrots, tomato sauce,and  liver spread. There are also regions in the Philippines that makes use of peanut butter.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Pork Caldereta.jpg'],
            ['name' => 'Pork Shang hai', 'description' => 'Lumpiang Shanghai is Filipino-style spring rolls made of ground pork, chicken, or beef filling wrapped in thin crepes called lumpia wrappers.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 1, 'menus_image' => 'Pork Shanghai.jpg'],
            
            ['name' => 'Shrimp Tempura', 'description' => 'Shrimp tempura is raw shrimp dipped into tempura batter and deep-fried in hot oil. The batter that is used to make the tempura consists of flour, water, cornstarch, and sometimes eggs.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 5, 'menus_image' => 'Crispy Prawn Tempura.jpg'],
            ['name' => 'Buttered Shrimp in Oyster Sauce', 'description' => 'This fried shrimp is further sauteed in a sauce made by sprite, butter, garlic, tomato paste, oyster sauce and spring onion', 'price' => 700, 'status' => 1, 'menu_selection_id' => 5, 'menus_image' => 'Buttered Shrimp in Oyster Sauce.jpg'],
            ['name' => 'Mixed Seafood Kare kare', 'description' => 'Seafood Kare kare is a delicious version of our beloved peanut stew using seafood such as shrimp, crab, mussels, and squid.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 5, 'menus_image' => 'Mixed Sea Food Kare Kare.jpg'],
           
            // ['name' => 'mixveg', 'description' => 'lorem ipsum', 'price' => 700, 'status' => 1, 'menu_selection_id' => 7, 'menus_image' => 'mixveg.jpg'],
            ['name' => 'Sippo Egg', 'description' => 'Sipo egg is a popular Kapampangan dish made with mixed vegetables and quail eggs smothered in a rich, creamy sauce.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 7, 'menus_image' => 'Sippo Egg.jpg'],
            ['name' => 'Chopsuey', 'description' => 'Chop Suey is a stir-fried vegetable dish that is cooked with meats such as chicken and pork. Shrimp and seafood can also be added. This chop suey recipe is special because it has almost every ingredient present. Chicken, pork, shrimp, and boiled quail eggs were all included in the recipe, along with fresh veggies.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 7, 'menus_image' => 'Chopsuey.jpg'],
            ['name' => 'Gising Gising', 'description' => 'Gising gising is a ground pork and green bean dish cooked in coconut milk. Shrimp paste (bagoong) is used to enhance the flavor.', 'price' => 700, 'status' => 1, 'menu_selection_id' => 7, 'menus_image' => 'Gising Gising.jpg'],
           
            
        ];

        foreach ($menusData as $menu) {
            Menu::create($menu);
        }
    }
}
